### ISSUE TITLE
add CI/CD to GitHub Pages

### ISSUE THREAD

**Issue by VadimLyashenko** [VadimLyashenko/gwt-examples#2]

**Comment by VadimLyashenko** [comment]
```
name: GWT Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get repository
        uses: actions/checkout@v3

      - name: setup Pages
        uses: actions/configure-pages@v3

      - name: install dependecies
        run: npm i

      - name: build app
        run: npm run build

      - name: upload a build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```
